### PR TITLE
Update for Strapi 3.5.1 + New Features

### PR DESCRIPTION
**Pull request by creazy231**
# ⚠️ Breaking Changes:

- You can't use `{{ variable }}` in email templates anymore.
Instead use original lodash templating syntax `<%= variable %>`.

# 🚀 New Features:

- Automatically adds `text` to your email if the template text is empty using `html-to-text` when using new `sendTemplatedEmail` function.
- Export & Import email templates
The import function overwrites templates with same id and template name and otherwise creates new entries.

# 🦊 Everything else

- added deprecated log to "old" `compose` and `send` function
- use `decode-html` to decode saved html body from database
- added cypress change language step to use english translation for tests

# 💭 Questions or Suggestions?
@all-contributors If you have any questions or suggestions for changes I've made, just let me know :)

### CODE REVIEW

**Review by alexzaganelli — CHANGES_REQUESTED** [review]
Hi @creazy231, great work, thank you.

I've checkout this pr (#18) to see the changes and I've found a couple of issues:

- I can't duplicate a template
- I can't remove a template

In addition I would suggest:
- For the created_at field would be great to use the same (moment) locale as strapi selected language
- Use translated strings for the Table headers and tooltips

**Comment by alexzaganelli** [comment]
I'll be able to fix the above from next week if not you before. Thank you again

**Comment by creazy231** [comment]
Thanks for your review @alexzaganelli 👍  sorry about the problems you have with this build. I thought I fixed that. I don't have much time this weekend but I can fix the issues you mentioned on Sunday afternoon.

**Comment by creazy231** [comment]
> * For the created_at field would be great to use the same (moment) locale as strapi selected language

I'm not an react expert and didn't find the official strapi method for locale timing. Would be awesome if you could tell me if you know.

**Comment by creazy231** [comment]
> * I can't duplicate a template

https://i.gyazo.com/c7f65e343c968fb4253c3ca7bf336583.mp4

> * I can't remove a template

https://i.gyazo.com/1dc1a443afa1798649b8590e71bf5062.mp4

> * For the created_at field would be great to use the same (moment) locale as strapi selected language

done

> * Use translated strings for the Table headers and tooltips

done

---
Could you tell me what exact problem you're facing when you want to duplicate or delete a template? As you can see in the videos I attached it's working for me but I changed the logic how modals get active because I had the issue that the modals didn't show.

**Comment by tbanys** [comment]
Hey guys, when do you planning to merge this PR?

**Comment by creazy231** [comment]
> Hey guys, when do you planning to merge this PR?

just had to fix some issues. Now I'm waiting for @alexzaganelli to confirm that everything works like expected and we should be good to go.

**Review by alexzaganelli — APPROVED** [review]
PR merged, thank you @creazy231

**Pull request closed without merging**
